apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: orders
  name: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: orders
    spec:
      containers:
      - image: orders:1.0.0
        name: orders
        resources: {}
status: {}
